INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(9, 'Free Culture', '2019-10-02 00:00:00', 'Critical look to the US Copyright Law and historic use', '/database/document/2019/freeculture.pdf', 'FILE');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(9, 'ILGA - State Sponsored Homophobia', '2019-10-05 00:00:00', 'A World Survey of Sexual Orientation Laws: Criminalisation, Protection and Recognition', 'database/document/2019/ILGA - State Sponsored Homophobia.pdf', 'FILE');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(11, 'Understanding Comics - McCloud', '2020-06-02 00:00:00', 'A look into the comics lenguage, using the same language', '/database/document/2020/Understanding Comics - McCloud.pdf', 'FILE');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(11, 'Shadow Play Girls - 1', '2020-06-02 00:00:00', 'かしら、かしら、ごぞんし　かしら？', '/database/image/2020/315201.jpg', 'PHOTO');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(11, 'Shadow Play Girls - 2', '2020-06-02 00:00:00', 'I wonder, I wonder, do you know what I wonder?', '/database/image/2020/315202.jpg', 'PHOTO');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(9, 'Utena - 1', '2019-03-20 00:00:00', 'Shoujo Kakumei Utena 1', '/database/image/2019/498919.jpg', 'PHOTO');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(9, 'Utena - 2', '2019-03-25 00:00:00', 'Shoujo Kakumei Utena 2', '/database/image/2019/498921.jpg', 'PHOTO');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(8, 'Entrevista Abuela Sonia Torres 2013', '2019-03-25 00:00:00', 'Shoujo Kakumei Utena 2', 'https://soundcloud.com/user-721144974/entrevista-abuela-sonia-torres-2013', 'AUDIO');
INSERT INTO abuelas.multimedia (id_actividad, nombre, fecha, descripcion, archivo, tipo) VALUES(8, 'A football game', '2019-03-25 00:00:00', 'Shoujo Kakumei Utena 2', 'https://youtu.be/Y07GHrnVsQ0', 'VIDEO');
